# Generated by Django 3.0.7 on 2020-06-23 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres', models.CharField(max_length=300)),
                ('sube_ismi', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Şube',
                'verbose_name_plural': 'Şubeler',
            },
        ),
        migrations.CreateModel(
            name='SubeTemsilcisi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinarspa_models.Sube')),
            ],
            options={
                'verbose_name': 'Şube temsilcisi',
                'verbose_name_plural': 'Şube temsilcileri',
            },
        ),
        migrations.CreateModel(
            name='Randevu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musteri_isim', models.CharField(max_length=50)),
                ('musteri_soyisim', models.CharField(max_length=50)),
                ('hizmet_turu', models.CharField(max_length=30)),
                ('tarih', models.DateTimeField()),
                ('secili_sube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinarspa_models.Sube')),
            ],
            options={
                'verbose_name_plural': 'Randevular',
            },
        ),
        migrations.CreateModel(
            name='MusteriGirisi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musteri_isim', models.CharField(max_length=50)),
                ('musteri_soyisim', models.CharField(max_length=50)),
                ('hizmet_turu', models.CharField(max_length=30)),
                ('giris_tarih', models.DateTimeField()),
                ('cikis_tarih', models.DateTimeField(blank=True, null=True)),
                ('ucret', models.IntegerField(default=0)),
                ('secili_sube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinarspa_models.Sube')),
            ],
        ),
    ]
