# Generated by Django 3.0.7 on 2020-06-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinarspa_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randevu',
            name='tarih',
            field=models.DateTimeField(),
        ),
    ]
