# Generated by Django 3.0.7 on 2020-06-30 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinarspa_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musterigirisi',
            name='musteri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinarspa_models.Musteri'),
        ),
        migrations.AlterField(
            model_name='randevu',
            name='musteri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinarspa_models.Musteri'),
        ),
    ]
