# Generated by Django 3.0.7 on 2020-06-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinarspa_models', '0002_auto_20200618_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='randevu',
            name='musteri_isim',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='randevu',
            name='musteri_soyisim',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
