# Generated by Django 3.0.7 on 2020-06-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinarspa_models', '0002_musterigirisi_calisan'),
    ]

    operations = [
        migrations.AddField(
            model_name='randevu',
            name='musteri_email',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
