# Generated by Django 3.0.7 on 2020-07-01 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinarspa_models', '0002_auto_20200630_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musteri',
            options={'verbose_name': 'Müşteri', 'verbose_name_plural': 'Müşteriler'},
        ),
        migrations.AlterModelOptions(
            name='musterigirisi',
            options={'verbose_name': 'Müşteri Girişi', 'verbose_name_plural': 'Müşteri girişleri'},
        ),
    ]
