# Generated by Django 3.0.7 on 2020-06-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinarspa_models', '0003_randevu_musteri_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='randevu',
            name='musteri_tel',
            field=models.CharField(default='', max_length=20),
        ),
    ]
