# Generated by Django 3.0.7 on 2020-07-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinarspa_models', '0004_subetemsilcisi_ustduzey_hak'),
    ]

    operations = [
        migrations.CreateModel(
            name='EkstraGider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=30)),
                ('detay', models.CharField(max_length=600)),
                ('tur', models.CharField(max_length=30)),
                ('tarih', models.DateTimeField()),
                ('tutar', models.IntegerField()),
            ],
        ),
    ]
