# Generated by Django 3.0.7 on 2020-06-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinarspa_models', '0004_randevu_musteri_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='musterigirisi',
            name='musteri_email',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='musterigirisi',
            name='musteri_tel',
            field=models.CharField(default='', max_length=20),
        ),
    ]
