# Generated by Django 3.0.7 on 2020-07-14 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinarspa_models', '0005_ekstragider'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekstragider',
            name='sube',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cinarspa_models.Sube'),
            preserve_default=False,
        ),
    ]
