# Generated by Django 3.0.7 on 2020-07-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinarspa_models', '0006_ekstragider_sube'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ekstragider',
            options={'verbose_name': 'Ekstra gider', 'verbose_name_plural': 'Ekstra giderler'},
        ),
        migrations.AddField(
            model_name='musteri',
            name='kredi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='musterigirisi',
            name='odeme_yontemi',
            field=models.CharField(default='Nakit', max_length=30),
        ),
    ]
