# Generated by Django 3.0.7 on 2020-07-29 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinarspa_models', '0007_auto_20200727_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusteriKredi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sayi', models.IntegerField(default=0)),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinarspa_models.Musteri')),
                ('sube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinarspa_models.Sube')),
            ],
        ),
    ]
