# Generated by Django 3.0.7 on 2020-07-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinarspa_models', '0008_musterikredi'),
    ]

    operations = [
        migrations.AddField(
            model_name='musterikredi',
            name='hizmet_turu',
            field=models.CharField(default='', max_length=50),
        ),
    ]
